/* V3.3: display-only estimates and Learn content. No store, clock, network or points.
   The caller supplies the exact displayed readings; formulas read the score engine's tables. */
(function(root,factory){
  if(typeof module==='object'&&module.exports)module.exports=factory(require('./scores.js'),require('./norms.js'));
  else root.GlowLearn=factory(root.Scores,root.Norms);
})(typeof globalThis!=='undefined'?globalThis:this,function(Scores,Norms){
  'use strict';
  const num=v=>typeof v==='number'&&Number.isFinite(v),round=v=>Math.round(v*10)/10;
  const ESTIMATES={vo2:{factor:15.3,hrIntercept:208,hrAge:0.7,minAge:18,maxAge:100,minRest:30,maxRest:120},forbes:{constantKg:10.4,sensitivity:0.2}};   // V3.4: the de Leva head share is gone (B7)
  const REFERENCES={bmi:[18.5,25,30]};
  // The adapter stores waist in inches; the score-range engine expects centimetres.
  const teachingValue=(metric,value)=>metric==='waist_circumference'&&num(value)?value*2.54:value;
  const teachingSeries=(rows,metric,growth)=>(rows||[]).filter(r=>num(r.v)&&(growth||!r.approx||!['heart_rate_variability','resting_heart_rate','respiratory_rate','blood_oxygen_saturation','apple_sleeping_wrist_temperature'].includes(metric))).map(r=>({...r,v:teachingValue(metric,r.v)}));
  function units(prefs){
    const metric=prefs&&prefs.units==='kg';
    return {mass:metric?'kg':'lb',length:metric?'cm':'in',distance:metric?'km':'mi',speed:metric?'km/h':'mph',
      kg:v=>num(v)?v*(metric?1:1/0.45359237):null,lb:v=>num(v)?v*(metric?0.45359237:1):null,
      cm:v=>num(v)?v/(metric?1:2.54):null,inch:v=>num(v)?v*(metric?2.54:1):null,
      meters:v=>num(v)?v/(metric?1000:1609.344):null,mph:v=>num(v)?v*(metric?1.609344:1):null,
      toLb:v=>num(v)?v/(metric?0.45359237:1):null,toInch:v=>num(v)?v/(metric?2.54:1):null};
  }
  function vo2Estimate(age,rhr){
    const t=ESTIMATES.vo2;
    if(!num(age)||age<t.minAge||age>t.maxAge||!num(rhr)||rhr<t.minRest||rhr>t.maxRest)return null;
    const hrMax=t.hrIntercept-t.hrAge*age;
    return {value:t.factor*hrMax/rhr,hrMax,rhr,age,estimated:true};
  }
  function vo2Choice(apple,rest,age){
    const estimate=rest?vo2Estimate(age,rest.value):null,fresh=!!apple&&num(apple.value)&&num(apple.age)&&apple.age>=0&&apple.age<=T().vo2.freshDays;
    return {apple,rest,estimate,fresh,value:fresh?apple.value:estimate?estimate.value:null,estimated:!fresh&&!!estimate,asOf:fresh?apple.day:estimate?rest.day:null};
  }
  /* Solve ΔW = ΔF + 10.4 ln(Fnew/Fold), Hall's finite-change Forbes relation.
     The displayed range varies the coefficient ±20%: sensitivity, NOT a confidence interval. */
  function companion(weightKg,fatPct,goalKg){
    if(!num(weightKg)||!num(fatPct)||!num(goalKg)||weightKg<=0||goalKg<=0||fatPct<=0||fatPct>=100||goalKg>=weightKg)return null;
    const fat=weightKg*fatPct/100,loss=goalKg-weightKg,t=ESTIMATES.forbes;
    const solve=c=>{let lo=Number.EPSILON,hi=fat;for(let i=0;i<80;i++){const mid=(lo+hi)/2;if(mid-fat+c*Math.log(mid/fat)>loss)hi=mid;else lo=mid;}const f=(lo+hi)/2;return {fatPct:100*f/goalKg,leanKg:goalKg-f};};
    const mid=solve(t.constantKg),ends=[solve(t.constantKg*(1-t.sensitivity)),solve(t.constantKg*(1+t.sensitivity))];
    if([mid,...ends].some(r=>!num(r.fatPct)||r.fatPct<0||r.fatPct>100||!num(r.leanKg)||r.leanKg<0||r.leanKg>goalKg))return null;
    return {...mid,fatRange:ends.map(x=>x.fatPct).sort((a,b)=>a-b),leanRange:ends.map(x=>x.leanKg).sort((a,b)=>a-b),sensitivity:t.sensitivity};
  }
  function vitals(rows){
    const present=(rows||[]).filter(r=>r.tone),steady=r=>r.ranked?!['red','orange'].includes(r.tone):r.tone==='green',calm=present.filter(steady).length;
    return {count:present.length,calm,share:present.length?calm/present.length:null,colour:!present.length?'neutral':calm===present.length?'green':calm===present.length-1?'yellow':'orange',outside:present.filter(r=>!steady(r)).map(r=>r.label)};
  }
  /* V3.4 (B7): the parts add up from the report itself. The five segments carry most of the fat and the muscle; the
     unsegmented remainder (head, neck and what Fitdays does not allocate) is (whole-body fat − segment fat) + (whole-body
     muscle − segment muscle); bone is its own line (fat-free weight − muscle mass). Fitdays' parts differ from its own
     weight by rounding (about a third of a pound); `other` absorbs it. This replaces the V3.3 de Leva head share. */
  function partition(report){
    const wb=report&&report.wholeBody,w=wb&&wb.weight,rows=report&&report.segments,val=k=>wb&&wb[k]&&num(wb[k].value)?wb[k].value:null;
    if(!w||w.unit!=='lb'||!num(w.value)||w.value<=0||!Array.isArray(rows)||rows.length!==5||rows.some(r=>!num(r.fatMassLb)||r.fatMassLb<0||!num(r.muscleBalanceMassLb)||r.muscleBalanceMassLb<0))return null;
    const fat=rows.reduce((a,r)=>a+r.fatMassLb,0),muscle=rows.reduce((a,r)=>a+r.muscleBalanceMassLb,0),total=fat+muscle,pct=val('bodyFatPercentage'),wholeFat=val('fatMass')!==null?val('fatMass'):pct!==null?w.value*pct/100:null,wholeMuscle=val('muscleMass'),ffw=val('fatFreeWeight');
    if(wholeFat===null||wholeMuscle===null)return {weight:w.value,fat,muscle,total,wholeFat,wholeMuscle,remainder:null,bone:null,other:null,reconciles:false,date:report.measurementDate};
    const remainder=(wholeFat-fat)+(wholeMuscle-muscle),bone=ffw===null?null:ffw-wholeMuscle,other=w.value-total-remainder-(bone||0);
    return {weight:w.value,fat,muscle,total,wholeFat,wholeMuscle,remainder,bone,other,reconciles:remainder>=-0.5&&(bone===null||bone>=0)&&Math.abs(other)<=1.5,date:report.measurementDate};
  }
  const SOURCES={
    friend:['FRIEND 2015 · treadmill reference standards','https://pubmed.ncbi.nlm.nih.gov/26455884/'],
    uth:['Uth et al. 2004 · heart-rate ratio method','https://pubmed.ncbi.nlm.nih.gov/14624296/'],
    tanaka:['Tanaka et al. 2001 · age-predicted maximum heart rate','https://pubmed.ncbi.nlm.nih.gov/11153730/'],
    hall:['Hall 2007 · Forbes body-composition model','https://pmc.ncbi.nlm.nih.gov/articles/PMC2376748/'],
    bmi:['CDC · adult BMI categories','https://www.cdc.gov/bmi/adult-calculator/bmi-categories.html'],
    waist:['NICE NG246 · waist-to-height ratio','https://www.nice.org.uk/guidance/ng246/chapter/Identifying-and-assessing-overweight-obesity-and-central-adiposity'],
    apple:['Apple · overnight vitals and typical ranges','https://support.apple.com/en-us/120142'],
    activity:['WHO · physical activity guidelines','https://www.who.int/publications/i/item/9789240015128'],
    sleep:['AASM/SRS · adult sleep duration consensus','https://pubmed.ncbi.nlm.nih.gov/26039963/'],
    voss:['Voss et al. 2015 · age and sex dependence of HRV','https://doi.org/10.1371/journal.pone.0118308'],
    pulse:['NCHS · resting pulse rate reference data','https://www.cdc.gov/nchs/data/nhsr/nhsr041.pdf'],
    fat:['Gallagher et al. 2000 · body-fat ranges','https://pubmed.ncbi.nlm.nih.gov/10966886/'],
    oxygen:['FDA · pulse oximeter limitations','https://www.fda.gov/consumers/consumer-updates/pulse-oximeter-basics'],
    cole:['Cole et al. 1999 · heart-rate recovery','https://pubmed.ncbi.nlm.nih.gov/10536127/']
  };
  const source=ids=>ids.map(id=>({name:SOURCES[id][0],url:SOURCES[id][1]}));
  const DISCLAIMER='For information, not medical advice. Estimates are not diagnoses or promised outcomes.';
  const T=()=>Scores.TABLE;
  // V3.6: the weights read as names, not the table's keys (the Health Age card said "vo2 40%, rhr 15%")
  const WEIGHT_NAMES={vo2:'VO₂ max',rhr:'resting heart rate',hrv:'HRV',bodyFat:'body fat',sleep:'sleep',steps:'steps',walk:'walking speed',load:'yesterday’s Load'};
  const weighted=w=>Object.entries(w).map(([k,v])=>(WEIGHT_NAMES[k]||k)+' '+round(v/Object.values(w).reduce((a,b)=>a+b,0)*100)+'%').join(', ');
  function recipes(){
    const t=T();
    return {
      weight:{name:'Weight & plan',line:'your dated scale reading against your own plan',what:'Weight is total body mass, not a direct measurement of fat. Short changes also reflect water and gut contents.',how:'The newest valid reading is converted only for display. The plan joins your starting weight and date to your chosen target and date; checkpoint marks follow dates, not pounds.',formula:'Plan = start + (goal − start) × elapsed days ÷ planned days.',optimal:'Your chosen goal is a plan, not a clinical optimal weight. Read BMI, waist and body composition alongside it.',why:'Repeated comparable readings are more informative than a single fluctuation. A straight plan line cannot predict how your body will respond.',improve:['Measure under similar conditions each time.','Compare a weekly trend, not one fluctuation.','Choose a sustainable plan with your clinician.'],sources:source(['hall','bmi']),related:['body-fat','lean-mass','bmi']},
      'body-fat':{name:'Body fat',line:'estimated fat as a share of total mass',what:'Body-fat percentage estimates the proportion of your weight that is fat. Smart-scale bioimpedance is an estimate, not a scan.',how:'Glow displays the latest imported percentage and dates it separately from weight. The range uses the existing age/sex reference table; an old reading is never silently made current.',formula:'Fat mass = weight × body-fat percentage ÷ 100; combine only comparable dated readings.',optimal:'See your age-band range above. Published ranges are broad reference bands; scale and DXA values are not interchangeable.',why:'It adds context to weight changes, but hydration, device algorithms and measurement conditions can change the estimate.',improve:['Compare the same scale under similar conditions.','Keep strength training alongside gradual weight changes.','Look for sustained trends before changing your plan.'],sources:source(['fat','hall']),related:['weight','lean-mass','waist'],footer:DISCLAIMER},
      'lean-mass':{name:'Lean mass',line:'mass other than fat—not the same as muscle',what:'Lean mass includes water, organs and other non-fat tissues. A change in lean mass is not automatically a change in muscle.',how:'The card uses the imported lean-body-mass reading. Regional Fitdays “lean muscle” estimates remain separate and keep their own report date.',formula:'Fat-free mass = total mass − fat mass; imported lean readings may use a different device model.',optimal:'There is no universal optimal lean mass. Your baseline, strength and chosen target are more useful than a made-up population grade.',why:'Tracking it alongside fat and weight can reveal whether a weight trend needs closer review. Hydration can move the number substantially.',improve:['Keep regular strength work in your routine.','Use comparable measurement conditions.','Review sustained losses with a qualified clinician.'],sources:source(['hall','activity']),related:['weight','body-fat','strength']},
      bmi:{name:'BMI',line:'weight relative to height, not body composition',what:'Body mass index relates mass to squared height. It is a screening measure and does not distinguish muscle from fat.',how:'Glow uses your stored height and latest weight. Display-unit changes never change the result.',formula:'BMI = weight in kg ÷ (height in metres)².',optimal:'CDC adult categories: underweight <18.5; healthy weight 18.5 to <25; overweight 25 to <30; obesity ≥30. These are screening categories, not a personal diagnosis.',why:'BMI provides one reference point, but can misclassify muscular builds. Waist and clinical context matter.',improve:['Check that your recorded height is correct.','Read waist and body composition alongside BMI.','Use clinician advice for an individual target.'],sources:source(['bmi','waist']),related:['weight','waist']},
      waist:{name:'Waist',line:'a direct measurement of central body size',what:'Waist circumference is a separate tape measurement. Glow does not predict waist from weight loss.',how:'Your latest waist measurement is converted for display. The goal remains yours to edit; a weight target never overwrites it.',formula:'Waist-to-height ratio = waist ÷ height, using the same unit.',optimal:'NICE advises keeping waist below half of height as a general guide. The Growth range uses its separately named reference table, not a prediction.',why:'Waist adds information about central adiposity that weight or BMI alone can miss. Measurement technique affects comparability.',improve:['Use the same tape placement each time.','Measure without pulling the tape tight.','Review waist with weight and clinical context.'],sources:source(['waist']),related:['weight','bmi','body-fat']},
      vo2:{name:'VO₂ max',line:'aerobic capacity: dated Watch value and a rough estimate',what:'VO₂ max estimates the oxygen you can use at maximal effort, relative to body mass. A Watch reading is not a laboratory test.',how:'A Watch reading no older than '+t.vo2.freshDays+' days leads. A resting-heart-rate estimate is shown alongside; when the Watch is older, only the clearly marked estimate is placed. Estimates never enter Health Age or points.',formula:'Estimate = '+ESTIMATES.vo2.factor+' × ('+ESTIMATES.vo2.hrIntercept+' − '+ESTIMATES.vo2.hrAge+' × age) ÷ resting HR. Uth ratio with Tanaka age-predicted HRmax.',optimal:'The displayed rung boundaries come from FRIEND 2015 for your configured age band. This is the deliberately retained yardstick, not the newest FRIEND edition.',why:'Cardiorespiratory fitness is useful context for training. The ratio method was studied in well-trained men; medications and individual heart-rate differences can make it inaccurate.',improve:['Build regular aerobic activity gradually.','Include easier days between harder sessions.','Prefer repeated Watch readings or a supervised test.'],sources:source(['friend','uth','tanaka']),related:['fitness-age','run-efficiency','recovery'],footer:DISCLAIMER},
      hrv:{name:'HRV',line:'overnight variation between heartbeats',what:'Heart-rate variability here is Watch SDNN in milliseconds. A personal baseline is more informative than competing with someone else’s value.',how:'Vitals uses the newest available overnight value; Growth uses the 30-day median. The typical box describes your own recent readings, while the rung is a rough population comparison.',formula:'Growth = median of eligible overnight SDNN values in the last 30 days.',optimal:'Your personal band leads. Voss reference values came from ECG recordings; the Watch protocol differs, so the population ladder is approximate.',why:'HRV can move with recovery, sleep and other factors; it cannot identify the cause of a change by itself.',improve:['Keep a steady sleep opportunity.','Compare several nights under similar conditions.','Balance demanding activity with easier days.'],sources:source(['voss','sleep']),related:['rhr','vitals','health-age']},
      rhr:{name:'Resting heart rate',line:'your resting pulse, with its own recent range',what:'Resting heart rate is the Watch’s daily estimate in beats per minute. Lower is not always healthier, especially with symptoms or medication effects.',how:'Vitals displays the newest daily reading; Growth grades the 30-day median. Glow shifts the seated NHANES reference by '+Norms.metrics.resting_heart_rate.shift+' bpm as an explicitly approximate Watch adjustment.',formula:'Growth = median of eligible daily resting-heart-rate values over 30 days.',optimal:'Read the personal band and age-band rung together. Very low or high values, particularly with symptoms, deserve clinical context—not a better score.',why:'A sustained departure from your normal can be worth noticing, but this reading does not diagnose illness or measure fitness on its own.',improve:['Watch the trend rather than one reading.','Allow recovery after demanding activity.','Discuss unusual readings or symptoms with a clinician.'],sources:source(['pulse']),related:['hrv','vitals','vo2']},
      breathing:{name:'Breathing rate',line:'overnight breaths per minute against your usual',what:'Breathing rate is breaths per minute during sleep. It is a personal-range flag, not an athletic ranking.',how:'Glow compares the latest overnight reading with your recent typical band. Early Warning uses at least '+t.warning.minNights+' nights and a high-side margin of max('+t.warning.rr+', '+t.warning.sds+' × robust SD).',formula:'High outlier ≥ prior median + max('+t.warning.rr+' breaths/min, '+t.warning.sds+' × robust SD).',optimal:'Your established personal range is the comparison. Lower numbers do not keep earning a better health grade.',why:'A sustained change can be useful context, but a wearable cannot explain why it happened.',improve:['Wear the Watch consistently during sleep.','Check whether a change persists across nights.','Seek care for breathing symptoms, regardless of this card.'],sources:source(['apple']),related:['vitals','sleep']},
      oxygen:{name:'Blood oxygen',line:'overnight oxygen estimates with device limitations',what:'Blood oxygen estimates saturation as a percentage. Consumer wearable readings may be affected by fit, motion and other measurement limitations.',how:'Glow uses eligible overnight readings and compares them with your own band. Early Warning’s low-side margin is max('+t.warning.spo2+', '+t.warning.sds+' × robust SD) after '+t.warning.minNights+' nights.',formula:'Low outlier ≤ prior median − max('+t.warning.spo2+' percentage points, '+t.warning.sds+' × robust SD).',optimal:'Compare with your established usual range. A displayed normal value does not rule out a problem.',why:'Use symptoms and clinical advice, not the wearable number alone, when deciding whether to seek care.',improve:['Check fit and measurement conditions.','Look for repeated rather than isolated changes.','Seek care for symptoms even if the reading looks normal.'],sources:source(['oxygen','apple']),related:['breathing','vitals']},
      vitals:{name:'Overall Vitals',line:'how many of the visible readings look steady',what:'This is a summary of the displayed Vitals rows, not a diagnosis or a separate physiological score.',how:'Ranked readings count as steady unless their rung is Poor or Below. Personal-range flags count only when green. Missing readings are excluded, never treated as healthy.',formula:'Steady share = steady visible readings ÷ all visible readings with a status. One non-steady row is yellow; two or more are orange.',optimal:'All available rows steady is green. A green summary still depends on how much data is available.',why:'The summary helps you find the individual reading worth opening. It does not replace reading the components or the separate Early Warning notice.',improve:['Open the named non-steady reading first.','Check its date and personal baseline.','Interpret persistent changes with clinical context.'],related:['hrv','rhr','breathing'],sources:source(['apple'])},
      rank:{name:'Overall Rank',line:'routine completion—not a measure of health',what:'Overall Rank describes completion of your required activities. It is independent of body measurements and medical fitness.',how:'Each included category contributes its completed share, weighted by the importance in Settings. Categories with nothing scheduled stay out of the average.',formula:'Overall = Σ(category completion % × configured importance) ÷ Σ(included importance). Grade boundaries come from Glow’s active rank table.',optimal:'Your own chosen routine is the target. A high grade does not establish good health, and missing a routine is not a medical failure.',why:'This is feedback on practice and consistency. It must not be confused with the population ladder or Health Age.',improve:['Start with the lowest-completion category above.','Make required routines realistic.','Exclude categories you do not want to grade.'],related:['growth','weight']},
      'health-age':{name:'Health Age',line:'Glow’s unvalidated weighted estimate, updated weekly',what:'Health Age is Glow’s heuristic summary of several measurements. It is not a validated biological age or a lifespan forecast.',how:'Each available factor is converted to a years offset. Missing factors are omitted and weights renormalized; the result updates each Monday using the preceding '+t.healthAge.window+' days.',formula:'Age + Σ(normalized weight × factor offset). Nominal weights: '+weighted(t.healthAge.weights)+'. Non-VO₂ standardized offsets use '+t.healthAge.perSd+' years per SD, capped at ±'+t.healthAge.clampSd+' SD; VO₂ offset is capped at ±'+t.healthAge.vo2Clamp+' years.',optimal:'There is no clinical optimal value for this heuristic. Compare its factors and confidence with your own prior values.',why:'It can summarize longer-term changes, but the weights and years scale are Glow’s method. A lower estimate does not promise lower risk.',improve:['Review the largest positive contribution above.','Build sustainable sleep and activity habits.','Use clinical measures for health decisions.'],sources:source(['friend','voss','pulse','fat']),related:['fitness-age','hrv','weight'],footer:DISCLAIMER},
      'fitness-age':{name:'VO₂ Age',line:'the reference age matching your VO₂ max',what:'VO₂ Age (once called Fitness age) is the age at which your VO₂ max matches the FRIEND 2015 male median. It is not your biological age.',how:'Glow linearly interpolates the reference anchors, extends the end slopes and caps the display. Only actual imported VO₂ readings qualify; the resting-HR estimate is excluded.',formula:'Interpolate (age, median VO₂): '+Norms.fitnessAge.anchors.map(a=>'('+a.join(', ')+')').join(', ')+'. Display limits '+Norms.fitnessAge.min+'–'+Norms.fitnessAge.max+'.',optimal:'A comparison with your actual age, not a clinical target. A reading over '+t.vo2.freshDays+' days old has low confidence; none within '+t.vo2.staleDays+' days means no value.',why:'It gives VO₂ max an intuitive reference, but a wearable estimate and population median cannot capture individual health.',improve:['Focus on sustainable aerobic consistency.','Keep the underlying VO₂ reading current.','Read the actual VO₂ trend alongside the age label.'],sources:source(['friend']),related:['vo2','health-age'],footer:DISCLAIMER},
      growth:{name:'Where I stand',line:'dated measurements against their named references',what:'Growth separates population ladders, target ranges and personal flags. They answer different questions and are not interchangeable.',how:'Each row reads its boundaries from the same reference table as its score. Steps use an activity index, HRV uses an approximate ECG comparison, and only VO₂ uses FRIEND.',formula:'Ranked rows use the highest eligible inclusive boundary. Target-range rows show distance to the nearest edge; flags compare with your baseline.',optimal:'There is no universal goal to make every row Elite. Some metrics have no Elite tier, and flags are never athletic ranks.',why:'Clear reference labels prevent a device estimate or a habit measure from looking like a laboratory assessment.',improve:['Choose one realistic area for improvement.','Read the source and confidence before comparing.','Compare like-for-like readings over time.'],sources:source(['friend','voss','pulse']),related:['vo2','hrv','health-age']},
      'run-efficiency':{name:'Run Efficiency',line:'metres travelled per heartbeat on qualifying easy runs',what:'This compares distance with heartbeats during easy runs. Heat, hills, pace and measurement errors can affect it.',how:'Runs need '+t.run.minMin+' minutes and '+t.run.minM+' metres, with heart rate '+t.run.easy.map(v=>round(v*100)).join('–')+'% of HRmax. Glow drops '+t.run.skip+' warm-up minutes and takes the median of at least '+t.run.minRuns+' runs in '+t.run.window+' days.',formula:'Efficiency = Σ minute distance (m) ÷ Σ minute heart rate (bpm). Trend compares the preceding '+t.run.window+' days; ±'+t.run.trendPct+'% defines a change.',optimal:'No population optimal range is claimed. Compare your own similar routes and conditions.',why:'It offers a repeatable training observation between VO₂ readings, not a validated fitness score.',improve:['Compare similar easy routes and conditions.','Keep easy efforts genuinely easy.','Inspect missing or unusual workout data.'],related:['vo2','durability'],sources:source(['activity'])},
      durability:{name:'Durability',line:'pace-to-heart-rate drift across a steady long run',what:'Durability here is cardiac drift: how distance per heartbeat changes from the first half to the second. Lower drift is not automatically better in every condition.',how:'Glow drops '+t.durability.skip+' minutes, splits eligible runs of at least '+t.durability.minMin+' minutes, and uses the median of '+t.durability.minRuns+' or more runs in '+t.durability.window+' days. Pace variation must be ≤'+round(t.durability.steadyCv*100)+'%.',formula:'Drift % = (first-half efficiency − second-half efficiency) ÷ first-half efficiency × 100. Gap limit '+t.durability.maxGapMin+' minutes. These eligibility rules and colour bands are Glow assumptions.',optimal:'Glow treats ≤'+t.durability.bands[0]+'% as steady; up to '+t.durability.bands[1]+'% yellow, up to '+t.durability.bands[2]+'% orange, then red. These are training heuristics, not clinical thresholds.',why:'Conditions, hydration and pacing affect drift. This view helps compare similar runs, not diagnose overtraining.',improve:['Compare long runs with similar weather and terrain.','Build duration gradually.','Review pacing before interpreting a changed score.'],related:['run-efficiency','vo2'],sources:source(['activity'])}
    };
  }
  function composedComponents(id,result){
    const t=T(),r=result||{},i=r.inputs||{},row=(key,name,value,max)=>({key,name,value:num(value)?value:null,max,colour:key==='consistency'?'violet':key==='interruptions'?'brass':'blue'});
    if(id==='readiness'){
      const subs=i.subs||{},w=t.readiness.weights,total=Object.keys(w).filter(k=>num(subs[k])).reduce((n,k)=>n+w[k],0),names={hrv:'HRV',rhr:'Resting heart rate',sleep:'Sleep',load:'Yesterday’s load'};
      return Object.keys(w).map(k=>row(k,names[k],num(subs[k])&&total?subs[k]*w[k]/total:null,num(subs[k])&&total?100*w[k]/total:0));
    }
    if(id==='sleep-score')return ['duration','consistency','interruptions'].map(k=>row(k,k[0].toUpperCase()+k.slice(1),i[k],t.sleep[k]));
    if(id==='fuel'){
      const food=num(i.outer),water=food?t.fuel.waterWeight:1,protein=(1-water)*t.fuel.proteinShare,calories=(1-water)*(1-t.fuel.proteinShare);
      return [row('water','Water',num(i.inner)?i.inner*water*100:null,water*100),row('protein','Protein',food?i.protein*protein*100:null,protein*100),row('calories','Calories',food?i.calories*calories*100:null,calories*100)];
    }
    if(id==='mobility'){const subs=i.subs||{},keys=Object.keys(subs);return keys.map(k=>row(k,{speed:'Walking speed',asymmetry:'Asymmetry',doubleSupport:'Double support',sixMinute:'Six-minute walk'}[k],subs[k]/keys.length,100/keys.length));}
    return [];
  }
  function dailyRecipes(){
    const t=T(),s=t.sleep,r=t.readiness,l=t.load,f=t.fuel,app='These are Glow’s operating rules, not validated clinical thresholds.',plain=['Check the dated input and its coverage first.','Compare like-for-like days instead of chasing a single number.','Choose a realistic routine; a score is not medical advice.'];
    const common={why:'This view makes the calculation inspectable. Missing inputs can change what a result means; the number alone does not establish a cause or a health outcome.',improve:plain,footer:DISCLAIMER};
    return {
      readiness:{...common,name:'Readiness',line:'today against your own baseline',what:'Readiness is Glow’s estimate of how current recovery signals compare with your recent baseline. It is not medical clearance to train.',how:'Eligible overnight HRV and resting heart rate are standardized against your own '+t.baselineDays+'-day history. At least '+r.minBaseline+' baseline days and a current HRV or resting-HR input are needed. Available components are renormalized; missing ones reduce confidence. Personal-vitals flags can cap the result at '+r.cap+'.',formula:'HRV z = '+r.z7+' × rolling z + '+r.z1+' × last-night z when both exist. HRV/RHR subscore = clamp('+r.centre+' + '+r.perZ+' × z, 0, 100). Weighted mean of available subscores: '+weighted(r.weights)+'. Prior-load subscore = clamp(100 − 100 × max(0, L − upper target)/max(upper target,1), 0,100). Round after any cap.',optimal:'There is no clinical optimal Readiness number. Read the displayed rating, confidence and weakest contributor together with how you feel. '+app,related:['sleep-score','load','hrv'],sources:source(['apple'])},
      'sleep-score':{...common,name:'Sleep score',line:'duration, timing and interruptions from the same night',what:'This is Glow’s score for the recorded sleep night, not a sleep study. Time in bed and time asleep are different; the score uses time asleep.',how:'Duration contributes up to '+s.duration+' points, bedtime consistency '+s.consistency+' and interruptions '+s.interruptions+'. Timing needs '+s.minNights+' nights in '+s.window+'. If timing is unavailable, the other two components are rescaled to 100. Missing wake segments use the existing one-wake fallback and lower confidence. Apple publishes the same component maxima, but Glow’s mappings and data are its own.',formula:'Duration = '+s.duration+' × clamp((hours asleep − '+s.floorH+')/(configured need − '+s.floorH+'),0,1). Consistency = '+s.consistency+' × clamp(('+s.sdZero+' − bedtime SD)/'+(s.sdZero-s.sdFull)+',0,1). Interruptions = clamp('+s.interruptions+' − '+s.perWake+' × max(0,wakes−1) − '+s.perWakeMin+' × max(0,awake minutes−'+s.freeWakeMin+'),0,'+s.interruptions+'). Add available points; without consistency divide by '+(s.duration+s.interruptions)+' and multiply by 100; round once.',optimal:'Your configured sleep need is the display target, not a diagnosis. AASM recommends adults regularly obtain at least 7 hours; individual needs vary. Glow’s score bands are app labels, not clinical thresholds.',why:'The three components distinguish a short night from irregular timing or recorded interruptions. A high wearable score cannot establish that sleep was restorative or rule out a sleep disorder.',improve:['Start with the lowest component shown above.','Keep a repeatable sleep opportunity and timing.','Discuss persistent sleep problems with a qualified clinician.'],related:['sleep-bank','readiness','sleep'],sources:[{name:'Apple · Sleep Score component maxima',url:'https://support.apple.com/en-euro/guide/watch/apded441a669/watchos'},{name:'AASM · adult sleep duration advisory',url:'https://aasm.org/advocacy/position-statements/adult-sleep-duration-health-advisory/'}]},
      'sleep-bank':{...common,name:'Sleep Bank',line:'a recency-weighted sleep balance, not weekly points credit',what:'Sleep Bank compares known sleep nights with your configured need, in hours. It is a separate heuristic from the weekly Sleep Credit used for points.',how:'The most recent '+s.bankNights+' nights contribute with descending weights. Missing nights are skipped, never replaced by zero hours. A positive bank is capped at '+s.bankCapH+' hours; negative debt is not capped. Coverage matters: a bank from one night is not a complete week.',formula:'Bank = min('+s.bankCapH+', Σ(('+s.bankNights+' − i)/'+s.bankNights+') × (sleep hours_i − configured need)), with i=0 for the newest night. Sum known nights only; no known nights means unknown.',optimal:'Zero means the weighted known nights meet your configured need. It is not proof of recovery, and extra recorded sleep is not permission to restrict future sleep. '+app,related:['sleep-score','readiness'],sources:[{name:'AASM · adult sleep duration advisory',url:'https://aasm.org/advocacy/position-statements/adult-sleep-duration-health-advisory/'}]},
      load:{...common,name:'Load',line:'comparable workout and everyday effort against your own band',what:'Load is Glow’s weighted activity total, not calories, distance or a medical measure of strain. A running day remains provisional.',how:'Workout minutes are weighted by heart rate when available, otherwise recorded effort or a labelled default. Everyday effort excludes workout windows. Until '+l.chronicMin+' complete days exist, both today and history use workouts only. Missing dates stay unknown; known rest days count as zero. The target uses a mean of at least '+l.chronicMin+' eligible days among the preceding '+l.chronic+'.',formula:'Workout zone floors (% HRmax → points/min): '+l.zones.map(x=>x.join(' → ')).join(', ')+'. Effort fallback floors → weights: '+l.effortWeights.map(x=>x.join(' → ')).join(', ')+'; default '+l.defaultWeight+'. Everyday effort floors → points/min: '+l.everyday.map(x=>x.join(' → ')).join(', ')+'. Target = eligible historical mean × Readiness band: '+Object.entries(l.bands).map(([k,v])=>k+' '+v.join('–')).join('; ')+'.',optimal:'The outlined interval is today’s personal app-defined target, not a universal safe dose. Deep blue is low, green is the actual target, red is high; symptoms and context matter more than the colour.',related:['readiness','recovery','strength'],sources:source(['activity'])},
      fuel:{...common,name:'Fuel',line:'water and food against the targets actually configured',what:'Fuel is completion against your water, protein and calorie targets. It does not judge food quality or establish nutritional adequacy.',how:'Bevel is the water source; locally logged water is used only when Bevel has none for that day. The food component needs both protein and calories with their targets; otherwise the result is explicitly Water only. A completed day with no water reading is unknown. A running day can show zero so far.',formula:'Water share = min(water/target,1). Protein share = clamp(protein/target,0,1). Calorie share = 1 within ±'+f.kcalFree+' kcal of target, otherwise max(0,1−(absolute gap−'+f.kcalFree+')/'+f.kcalSlope+'). Food = '+f.proteinShare+' × protein + '+(1-f.proteinShare)+' × calories. Fuel = round(100 × ('+f.waterWeight+' × water + '+(1-f.waterWeight)+' × food)); Water only = round(100 × water). Default protein target = '+f.proteinPerKg+' × recorded kg unless set. Fallback calorie target = known burn mean of the prior '+f.burnDays+' days (minimum '+f.burnMin+') plus your Net Energy goal (a negative number: the deficit you chose).',optimal:'100 means the app’s targets were met, not a clinical optimum. These targets are configurable; the protein multiplier and calorie tolerance are Glow defaults, not individualized dietary advice.',related:['energy-weight','weight','load']},
      faith:{...common,name:'Faith ring',line:'the share of planned prayers, fast and church recorded as kept',what:'The Faith ring reflects the selected day’s planned practices. It does not measure faith, spiritual worth or the quality of prayer.',how:'Only planned prayers, fasting and church enter this ring. The church calendar can supply the planned fast. Done contributes one; Partial contributes its recorded share. Excused and rest entries leave the denominator. Nothing planned means unknown rather than a failed day. This ring never contributes to Readiness.',formula:'Faith % = round(100 × Σ(done credit)/(planned, non-excused items)). Done=1; Partial=clamp(recorded percentage/100,0,1); otherwise 0. The active daily plan and dated outcomes determine which items count.',optimal:'Your freely chosen, realistic practice is the reference. The ring stays royal purple; no red/green health grade is assigned.',why:'The ring can remind you what you intended and what you recorded. It cannot interpret spiritual meaning, and a blank or skipped practice is not a judgment of you.',improve:['Review the next open practice you actually intend to keep.','Correct missing or mistaken entries when helpful.','Adjust future plans when circumstances change.'],related:['readiness',{name:'Faith',area:'faith'}]},
      'energy-weight':{...common,name:'Energy & Weight',line:'reported energy balance and a separately drawn personal weight plan',what:'Energy balance compares reported food with reported resting and active energy. Weight is plotted from eligible measurements; neither is an exact measurement of fat change.',how:'A displayed deficit requires readable food and energy records for that date. Source estimates and incomplete logging can change it. Recorded weights stay separate from the dashed personal plan and outlined saved goal. Manual observations and eligible imports are preserved, with history-day means marked approximate. An adaptive burn estimate is not implemented.',formula:'Net Energy kcal = food energy − (resting energy + active energy); below zero is a deficit. One convention everywhere: negative is a deficit (red, left of zero or below the line), positive a surplus (blue). Each day’s net is rounded first; the selected-range daily mean averages those displayed values, then rounds once more. A day counts only with a full record (food, resting and active energy); a missing input is named, never read as zero. On track is a net at or below your saved on-track threshold; the goal is your saved Net Energy goal. Weight estimate = last weigh-in + Σ(food − resting − active) since ÷ 3,500 kcal a pound, an unlogged day counted as no food; the logging gap is the scale minus that estimate. Planned weight on date d = start weight + (goal−start weight) × clamp((d−start date)/(goal date−start date),0,1). No missing measurement is manufactured from the plan.',optimal:'The saved weight and deficit goals are personal settings, not clinical ideal values. A missing day or an incomplete food log cannot establish an energy deficit.',improve:['Check that the food and both energy inputs cover the date.','Compare actual dated measurements with the separate saved plan.','Review a realistic goal with appropriate professional guidance.'],related:['weight','fuel',{name:'Goals',area:'profile'}]}
    };
  }
  function cards(readings,ids){
    const catalog=recipes(),t=T();
    const extra={
      steps:['Daily steps','your average activity, not a population percentile','The 30-day mean of daily totals. The ladder uses Tudor-Locke’s activity index; Athlete is Glow’s estimate and there is no Elite tier.','Mean steps = sum of known daily totals ÷ known days. Missing days are not zero.','Use your own achievable activity target; more is not always better.'],
      sleep:['Sleep','time asleep compared with your chosen need','The Sleep score combines duration, timing consistency and interruptions; Growth’s range row is the 30-night mean duration.','Score maxima: duration '+t.sleep.duration+', consistency '+t.sleep.consistency+', interruptions '+t.sleep.interruptions+'. Timing uses '+t.sleep.window+' nights with at least '+t.sleep.minNights+' nights.','The adult reference is 7–9 hours; your goal is separately editable.'],
      recovery:['Recovery Speed','the first minute after a qualifying workout','A recency-weighted 60-second heart-rate drop over '+t.recovery.windowDays+' days. Hard finishes qualify at '+round(t.recovery.hardShare*100)+'% of HRmax, not heart-rate reserve. The easier-finish fallback is never ranked.','Primary: weighted mean(end HR − interpolated HR at 60 s), in bpm. Easier-finish fallback: weighted mean of 100 × (end HR − HR60)/(end HR − resting HR), in % of reserve recovered, not graded. Weight = 0.5^(days ago ÷ '+t.recovery.halfLifeDays+'); at least '+t.recovery.minSessions+' sessions.','The source protocol and Glow’s Watch protocol differ; ladder boundaries beyond the clinical flag are estimates.'],
      readiness:['Readiness','today against your own baseline','Glow blends HRV, resting heart rate, sleep and prior-day load, then applies personal-vitals caps. This is a training heuristic, not a medical clearance.','Nominal weights: '+weighted(t.readiness.weights)+'. Centre '+t.readiness.centre+'; '+t.readiness.perZ+' points per standardized deviation. Missing components lower confidence.','Use the score with how you feel and with the component breakdown.'],
      strength:['Strength Balance','how regularly you include strength days','Counts qualifying strength days, not workout count or strength performance.','100 × min(1, strength days ÷ '+t.strength.targetDays+') across '+t.strength.window+' days.','Glow’s target is '+t.strength.targetDays+' days in '+t.strength.window+' days; it is routine balance, not measured strength.'],
      mobility:['Mobility','walking speed and steadiness, not a diagnosis','Averages whichever walking components are available; at least two are needed. The six-minute-walk prediction is a reference, not an individualized prescription.','Each component is 100 × clamp(ratio, 0, 1); average at least two. Speed ratio = (m/s − '+t.mobility.speed[0]+')/('+t.mobility.speed[1]+' − '+t.mobility.speed[0]+'); asymmetry = ('+t.mobility.asymmetry[0]+' − value)/'+t.mobility.asymmetry[1]+'; double support = ('+t.mobility.doubleSupport[0]+' − value)/'+t.mobility.doubleSupport[1]+'; six-minute walk = (distance − LLN)/'+t.mobility.walkSpan+'. LLN = 7.57 × height cm − 5.02 × max(age,40) − 1.76 × weight kg − 309 − '+t.mobility.walkSpan+' metres (Enright male reference).','A floor check is not a population percentile. Individual limitations deserve clinical context.']
    };
    for(const [id,[name,line,how,formula,optimal]] of Object.entries(extra))catalog[id]={name,line,what:line.charAt(0).toUpperCase()+line.slice(1)+'. This view summarizes eligible readings, not missing data.',how,formula,optimal,why:'Compare like-for-like records over time. The score is a prompt to inspect its inputs, not proof of a cause or a promised outcome.',improve:['Check the weakest available component above.','Build a repeatable, sustainable routine.','Review unusual changes with appropriate clinical advice.'],related:['growth','health-age'],sources:source(id==='sleep'?['sleep']:id==='recovery'?['cole']:['activity'])};
    Object.assign(catalog,dailyRecipes());
    return ids.filter(id=>catalog[id]).map(id=>{const r=readings[id]||{},c=catalog[id];return {...c,id,
      score:{value:r.value===undefined?null:r.value,word:r.word||'No reading yet',colour:r.colour||'neutral',change:[r.asOf?'as of '+r.asOf:null,r.change,r.confidence?'confidence '+r.confidence:null].filter(Boolean).join(' · '),ring:r.ring||{id:'learn-'+id,share:null,centre:r.value===null||r.value===undefined?'—':String(r.value).split(' ')[0],title:c.name,label:c.name+': '+(r.value??'no reading')+'; no clinical grade inferred'}},
      moved:r.moved||'No comparable earlier result is available to identify a mover.',breakdown:r.breakdown&&r.breakdown.length?r.breakdown:[{name:'Latest result',yours:r.value??'—',weight:r.asOf||'not available'},{name:'Coverage',yours:r.confidence||'Unknown',weight:'missing is not zero'},{name:'Method',yours:'Glow’s method',weight:'see calculation below'}],compare:r.compare||'<p class="hint">No comparable earlier readings are available for a chart.</p>',optimal:r.optimal||c.optimal,optimalVisual:r.optimalVisual||'<p class="hint">No personal clinical optimal range is inferred for this measure.</p>',improve:r.improve||c.improve,footer:c.footer||DISCLAIMER};});
  }
  return {ESTIMATES,REFERENCES,SOURCES,teachingValue,teachingSeries,units,vo2Estimate,vo2Choice,companion,vitals,partition,recipes,composedComponents,cards};
});
